"""
Django settings for coupon_project project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

import os
from pathlib import Path
from datetime import timedelta

# =========================
# 基础路径配置
# =========================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# 安全相关（开发环境）
# =========================

# ⚠️ 生产环境必须放到环境变量
SECRET_KEY = 'django-insecure-i!-p=r7nb*_+^0%68(1o3$h4_e0yant%ugsbg7+n=f6xqw2h1a'

DEBUG = True

ALLOWED_HOSTS = [
    "111.229.227.182",
    "localhost",
    "127.0.0.1",
]


# =========================
# 应用注册
# =========================

INSTALLED_APPS = [
    # Django 内置
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方
    'rest_framework',          # DRF 核心
    'drf_yasg',                # Swagger 文档

    # JWT 黑名单（用于封号 / 强制下线）
    'rest_framework_simplejwt.token_blacklist',

    # 业务应用
    'coupons',
]

# 使用自定义用户模型
AUTH_USER_MODEL = 'coupons.User'


# =========================
# 中间件
# =========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 管理后台仍可用
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',              # JWT 接口不依赖 CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================
# URL / WSGI
# =========================

ROOT_URLCONF = 'coupon_project.urls'
WSGI_APPLICATION = 'coupon_project.wsgi.application'


# =========================
# 模板（保留 admin）
# =========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================
# 数据库（当前 sqlite，后续可换 MySQL / PG）
# =========================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =========================
# 密码校验
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =========================
# 国际化
# =========================

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# =========================
# 静态文件
# =========================

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")


# =========================
# 默认主键
# =========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =====================================================
# DRF 核心配置（JWT 版本）
# =====================================================

REST_FRAMEWORK = {
    # API 文档 Schema
    # drf_yasg / swagger 使用
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",

    # 默认权限
    # 所有接口默认需要登录
    # 登录 / 注册接口需在 view 中显式 AllowAny
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    # 认证方式
    # 只使用 JWT，不再使用 Session / Token
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    # 分页
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,

    # 时间格式
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",

    # Renderer
    # 生产环境建议只保留 JSONRenderer
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # "rest_framework.renderers.BrowsableAPIRenderer",  # 开发调试可打开
    ],

    # Parser
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}


# =====================================================
# JWT（SimpleJWT）参数配置
# ⚠️ 注意：不放在 REST_FRAMEWORK 里
# =====================================================

SIMPLE_JWT = {
    # access token：接口访问用
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),

    # refresh token：刷新 access 用
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # 每次刷新 refresh 时生成新的 refresh
    'ROTATE_REFRESH_TOKENS': True,

    # 旧 refresh 加入黑名单（需要 token_blacklist）
    'BLACKLIST_AFTER_ROTATION': True,

    # JWT 签名算法
    'ALGORITHM': 'HS256',

    # 使用 Django SECRET_KEY 签名
    'SIGNING_KEY': SECRET_KEY,

    # 请求头格式
    # Authorization: Bearer <access_token>
    'AUTH_HEADER_TYPES': ('Bearer',),

    # 用户标识字段
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
