# Generated by Django 5.2.9 on 2026-01-02 08:35

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('roles', models.JSONField(default=list)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_count', models.PositiveIntegerField(default=1, help_text='可核销次数')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2026, 3, 3, 23, 59, 59))),
                ('used_first_order_rule', models.BooleanField(default=False, help_text='是否已使用首单优惠规则')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商家名称', max_length=100)),
                ('phone', models.CharField(default='00000000000', help_text='联系电话', max_length=20)),
                ('credit_code', models.CharField(blank=True, help_text='社会统一信用代码', max_length=50, null=True)),
                ('license', models.FileField(blank=True, help_text='营业执照（图片或PDF，不超过20M）', null=True, upload_to='licenses/')),
                ('id_card', models.FileField(blank=True, help_text='法人身份证（图片，不超过2M）', null=True, upload_to='id_cards/')),
                ('store_photos', models.JSONField(blank=True, default=list, help_text='门店照片列表（图片）')),
                ('logo', models.FileField(blank=True, help_text='LOGO图片', null=True, upload_to='logos/')),
                ('promo_images', models.JSONField(blank=True, default=list, help_text='宣传图片列表')),
                ('contact_name', models.CharField(blank=True, help_text='联系人姓名', max_length=50, null=True)),
                ('business_hours', models.CharField(blank=True, help_text='营业时间', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='店铺地址', max_length=200, null=True)),
                ('store_type', models.CharField(blank=True, choices=[('clothing', '服装鞋饰'), ('food', '餐饮美食'), ('entertainment', '休闲娱乐'), ('supermarket', '商超便利'), ('digital', '数码家电'), ('beauty', '美妆个护'), ('home', '家居生活'), ('baby', '母婴亲子'), ('sports', '运动户外'), ('health', '健康医药'), ('auto', '汽车出行'), ('education', '教育培训'), ('pet', '宠物生活'), ('hardware', '建筑五金')], help_text='店铺类型', max_length=20, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.08, help_text='抽成比例，默认8%', max_digits=5)),
                ('total_card_sold', models.PositiveIntegerField(default=0, help_text='售卡数量')),
                ('total_card_revenue', models.DecimalField(decimal_places=2, default=0, help_text='售卡收入', max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='总流水金额', max_digits=12)),
                ('total_redemptions', models.PositiveIntegerField(default=0, help_text='总核销次数')),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, help_text='平均客单价', max_digits=12)),
                ('today_revenue', models.DecimalField(decimal_places=2, default=0, help_text='今日营业额', max_digits=12)),
                ('today_orders', models.PositiveIntegerField(default=0, help_text='今日客单量')),
                ('today_avg_order_value', models.DecimalField(decimal_places=2, default=0, help_text='今日客单价', max_digits=12)),
                ('first_order_active', models.BooleanField(default=True, help_text='首单优惠是否开启')),
                ('approved', models.BooleanField(default=False, help_text='是否审核通过')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('full_reduce', '满减'), ('discount', '折扣'), ('old_customer', '老客户立减')], max_length=20)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='merchant_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='coupons.merchant'),
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.couponrule')),
                ('membership_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.membershipcard')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=1.8, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded', models.BooleanField(default=False)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
