# Generated by Django 5.2.9 on 2026-01-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_user_phone_user_wechat_openid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponrule',
            old_name='discount_percent',
            new_name='discount_rate',
        ),
    ]
